version: "3.9"
services:
  frontend-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/frontend-debug:${TAG}
    ports:
      - 6502:6502
      - 6512:6512
    
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/frontend:${TAG}
